{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-user-microservice-pvc
  labels:
    app: user-microservice
    release: {{ .Release.Name }}
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
