apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-user-microservice-secret
  labels:
    app: user-microservice
    release: {{ .Release.Name }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  admin-username: {{ .Values.secrets.adminUsername | b64enc | quote }}
  admin-password: {{ .Values.secrets.adminPassword | b64enc | quote }}
